### ISSUE TITLE
CLIP Results Different in Eff Loader Than Other CLIP Nodes

### ISSUE THREAD

**Issue by Kinglord** [jags111/efficiency-nodes-comfyui#1]
I have some pictures and some more details around my initial investigation here - https://github.com/LucianoCirino/efficiency-nodes-comfyui/issues/201#issue-1949788433

Right now the way Eff Loader Interprets CLIP text is different from other CLIP Encoder nodes. I'm not sure what's going on but it seems to affect some LORAs especially hard (making dialing in CLIP STR almost impossible), but it affects all images and checkpoints to some degree.

In someone only uses Eff nodes for all clip encoding in theory this might not be a major issue, but anytime nodes are mixed it can create adverse effects. Happy to provide more details if needed or generate some new examples.

I discovered this trying to use the XY Lora Plot scripts, which highlights the issue quite prominently and also makes the results from it unusable (unless you're using an eff loader to always apply your lora clip)

**Comment by jags111** [comment]
for sure any details on this including some example will help pin point the same and take this forward or correct the code for the clip Encoder nodes. Thanks and will take this up

**Comment by Kinglord** [comment]
Sure, let me pull this version and generate an example WF just in case you're fixes magically fixed this as well :D

**Comment by jags111** [comment]
I have tested many of similar XY plots and may be the design of the script is done like that. Any suggestions to add or change code appreciated and will follow same.
![Eff_XYPlot - Seeds vs Checkpoints   Stacked ScriptsWF](https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/38549ef5-2a1f-49ab-bd0c-95d0126cec36)

**Comment by jags111** [comment]
I am aware of same and will update on this so the nodes will be working with enhanced clip results
