### ISSUE TITLE
A few hours ago comfy changed the content in samplers.py, which resulted in errors like cannot import name 'CompVisVDenoiser' from 'comfy.samplers'

### ISSUE THREAD

**Issue by suede299** [jags111/efficiency-nodes-comfyui#10]
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/85022330/6ebde230-cd49-455b-abe3-e4ed9d86cc7e)
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/85022330/c06929cd-c342-4469-80a9-bd50220feeb5)

**Comment by noahjgreer** [comment]
Yes, this seems to have caused an issue with importing the Efficiency Nodes module. Any ideas on how to fix it?

**Comment by jags111** [comment]
I am on it to see if there is a workaround for same . else the node will be paused until rest workflow will continue.. The change in comfy sampler code  will not allow CompVisDenoiser  to work so have to add another module or new script to handle same.

**Comment by lord-lethris** [comment]
I have the same issue - I posted it here first.  

https://github.com/LucianoCirino/efficiency-nodes-comfyui/issues/235

I didn't know about this Branch of the project :)
I hope its fixable.  in the interim, I might see if I can roll back the breaking Commit from ComfyUI.

**Comment by jags111** [comment]
will check as for now the particular node is throwing errors and will fix same and update.

**Comment by picobyte** [comment]
pip install k-diffusion and
```
diff --git a/py/smZ_cfg_denoiser.py b/py/smZ_cfg_denoiser.py
index e6a4ce1..dfe3b5f 100644
--- a/py/smZ_cfg_denoiser.py
+++ b/py/smZ_cfg_denoiser.py
@@ -4,8 +4,8 @@ import torch
 from typing import List
 import comfy.sample
 from comfy import model_base, model_management
-from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
-from comfy.k_diffusion.external import CompVisDenoiser
+from comfy.samplers import KSampler, KSamplerX0Inpaint
+from k_diffusion.external import DiscreteVDDPMDenoiser,CompVisDenoiser
 import nodes
 import inspect
 import functools
@@ -17,6 +17,15 @@ import itertools
 import torch
 from comfy import model_management
 
+
+class CompVisVDenoiser(DiscreteVDDPMDenoiser):
+    def __init__(self, model, quantize=False, device='cpu'):
+        super().__init__(model, model.alphas_cumprod, quantize=quantize)
+
+    def get_v(self, x, t, cond, **kwargs):
+        return self.inner_model.apply_model(x, t, cond, **kwargs)
+
+
 def catenate_conds(conds):
     if not isinstance(conds[0], dict):
         return torch.cat(conds)
@@ -318,4 +327,4 @@ def set_model_k(self: KSampler):
 class SDKSampler(comfy.samplers.KSampler):
     def __init__(self, *args, **kwargs):
         super(SDKSampler, self).__init__(*args, **kwargs)
-        set_model_k(self)
\ No newline at end of file
+        set_model_k(self)
```

**Comment by jags111** [comment]
oh will look into this again and update

**Comment by jags111** [comment]
all sorted and if any further open a new issue

**Comment by h3clikejava** [comment]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/h3c/Documents/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/h3c/Documents/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/h3c/Documents/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 700, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 503, in process_latent_image
    positive_hash = tensor_to_hash(positive[0][0])
  File "/home/h3c/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui/tsc_utils.py", line 96, in tensor_to_hash
    byte_repr = tensor.cpu().numpy().tobytes()  # Convert tensor to bytes
AttributeError: 'NoneType' object has no attribute 'cpu'

**Comment by sapientsnap** [comment]
Thanks @jags111 for engineering and posting this. 
But... I'm not quite sure what to do with that code you pasted. 
I ran pip install k-diffusion, but the loading error still occurs, so I assume that code needs to be put somewhere?

Thanks for any assist.
