### ISSUE TITLE
efficiency nodes don't install correctly. no error message

### ISSUE THREAD

**Issue by sirus20x6** [jags111/efficiency-nodes-comfyui#104]
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/5103327/8f24b059-21f8-4aab-ab46-636b000a2760)

I get no error on the command line where comfui is running from. installing these custom nodes does not make them show up. 

trying to run this workflow from the example images does not load the models.
![Eff_XYPlot - LoRA Model vs Clip Strengths01](https://github.com/jags111/efficiency-nodes-comfyui/assets/5103327/61914a37-67bd-468f-8440-0f46f2707cdd)

running fix does not fix the nodes.
no error message of any kind
on arch linux.

**Comment by ravaan** [comment]
I believe I am facing similar issue, AnimateDiff Scripts node is not loading even tho I have tried, reinstalling, fixing, going to the original repo where this was forked from etc 

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/15053720/e38a4ec8-1ab3-446b-a803-22776512b6ff)

**Comment by jags111** [comment]
please note animate diff script is not being installed as i deprecated same. The new animate diff evolved is more complex to be called in scripts
best is to add a link in the script for same which will do so after it settles down
