### ISSUE TITLE
Conflicted nodes

### ISSUE THREAD

**Issue by HeavyTony2** [jags111/efficiency-nodes-comfyui#107]
Those following nodes are listed as conflicted:
`Image Overlay [Comfy_KepListStuff], NNLatentUpscale [ComfyUi_NNLatentUpscale], LatentUpscaler [SD-Latent-Upscaler]`

**Comment by jags111** [comment]
will see this

**Comment by jags111** [comment]
the same will be solved by comfy Manager

**Comment by 6sixteen** [comment]
Was **LatentUpscaler** changed to **TSC_HighRes_Fix**?
