### ISSUE TITLE
'SDXLRefinerClipModel' object has no attribute 'clip_l'

### ISSUE THREAD

**Issue by dreetie** [jags111/efficiency-nodes-comfyui#13]
When using a SDXL refiner I get the error:

Error occurred when executing Eff. Loader SDXL:

'SDXLRefinerClipModel' object has no attribute 'clip_l'

I use the example workflow "SDXL Refining & Noise Control Script" found in this repo

**Comment by jags111** [comment]
okay will review this issue and update

**Comment by Layer-norm** [comment]
Try to add or update this node https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb.git .I have met this bug few days ago

**Comment by kakachiex2** [comment]
I' have this same problem SDXLRefinerClipModel' object has no attribute 'clip_l'

**Comment by slimanibenbadis** [comment]
Hi, same issue here.
It happened after I updated ComfyUI.
It stop at the Eff. SDXL Loader node.

Very troublesome since my whole workflow depends on this node

**Comment by slimanibenbadis** [comment]
More precision on this to help resolve this.
I got back to the commit where @LucianoCirino said he will not work on this anymore to see if it works.
It happens that when I did and restarted Comfy, it colored the Eff. Nodes in red like if they were missing.

Then I got back to the Comfy version of the same day I got back with the extension, and it worked. 

I think the bug got in between today and 30 oct. (the day I got my versions back)

**Comment by dnl13** [comment]
if you like you can grab the 
https://github.com/dnl13/efficiency-nodes-comfyui/blob/main/py/bnk_adv_encode.py
from my fork. 
I have already fixed this some days ago.

**Comment by slimanibenbadis** [comment]
> if you like you can grab the https://github.com/dnl13/efficiency-nodes-comfyui/blob/main/py/bnk_adv_encode.py from my fork. I have already fixed this some days ago.
> 
> @jags111 not merging ? #9

Was going to check this myself, but didn't see your PR, thanks a lot you saved me time investigating since I am not used to Python ;) 

By merging the PR, it fixes this issue @jags111 

Thank you all.

**Comment by jags111** [comment]
I am checking same and will be merged now so it can solve same

**Comment by jags111** [comment]
already resolved and please check if the same is working and update.. If any further need to check the error in detail so can find the solution. Please post the capture from your log file to update

**Comment by dreetie** [comment]
updated and now the error is gone, many thanks

**Comment by jags111** [comment]
already we have resolved same.
