### ISSUE TITLE
KSampler

### ISSUE THREAD

**Issue by alexbofa** [jags111/efficiency-nodes-comfyui#139]
Hello, there is a problem with **KSampler (Efficient)**. 

If the seed is fixed, then it does not generate any changes outside the **KSampler (Efficient)**, only if some value is entered in the **KSampler (Efficient)**. Example: 30 steps → 29 steps

**Comment by jags111** [comment]
<img width="931" alt="2024-04-06_10-17-30" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/646d69a3-1c6c-4ee9-a8ee-859f8609f1b0">
