### ISSUE TITLE
module 'comfy.sample' has no attribute 'prepare_mask'

### ISSUE THREAD

**Issue by taylenhe20240219** [jags111/efficiency-nodes-comfyui#151]
Error occurred when executing KSampler:
module 'comfy.sample' has no attribute 'prepare_mask'

The plug-in is already the latest, what should be done specifically?

**Comment by jags111** [comment]
not sure on this and can you add more details as not sure where this error is coming form . I will need either the detailed error info or workflow to ascertain the cause.
