### ISSUE TITLE
module 'comfy.sample' has no attribute 'prepare_mask'

### ISSUE THREAD

**Issue by vstone2024** [jags111/efficiency-nodes-comfyui#155]
![微信图片_20240410232242](https://github.com/jags111/efficiency-nodes-comfyui/assets/165302240/3ca740a5-6bd1-4dbe-919d-a37f190f55fe)
If I upgrade ComfyUI to a version above the current one, the ksample efficiency node encounters an error; however, it operates smoothly on my work computer. Both my home and work computers run Windows 11 systems. Despite copying the ComfyUI installation from my work computer to my home setup, the same error persists. I have also attempted to uninstall and reinstall the node, but this measure did not resolve the problem. As of now, the only way I can use the software without encountering errors at home is by refraining from upgrading ComfyUI to the latest version. The exact cause of this discrepancy remains unclear.
![微信截图_20240410233346](https://github.com/jags111/efficiency-nodes-comfyui/assets/165302240/5d169827-7310-4511-aefa-756d6e6a813e)

**Comment by jags111** [comment]
hai will look into this and update

**Comment by jags111** [comment]
already this is resolved from updates
