### ISSUE TITLE
Could We Add an Option for Hierarchical Lora Selection Interface and Preview Functionality

### ISSUE THREAD

**Issue by lfeng35** [jags111/efficiency-nodes-comfyui#163]
Hello Developers,

I have a quick suggestion concerning the Lora selection interface.

Currently, I'm dealing with several hundred Lora files stored in various folders. However, the current setup lists all Lora selections together in one long list. This makes it quite cumbersome for me to navigate through them, as I have to scroll through a large number of options every time.

Could we possibly add an option to display Lora selections in a hierarchical manner, organized by their respective folders? This would greatly improve usability and streamline the selection process.

Additionally, it would be immensely helpful to have preview options available for both Lora and checkpoints, aiding in easier and more efficient selection.

I've attached an example below for reference, showcasing the desired hierarchical display. (The Lora loader node is from https://github.com/pythongosssss/ComfyUI-Custom-Scripts)

Your consideration of this request would be greatly appreciated.

Thank you for your attention to this matter.

![1](https://github.com/jags111/efficiency-nodes-comfyui/assets/65928167/77172a42-bed9-4797-b5ad-e13e0fd845d6)

**Comment by jags111** [comment]
we will try but the node code will be rewritten for same. it is better to select based on the folder structure you have.
