### ISSUE TITLE
AttributeError: module 'efficiency-nodes-comfyui.py.smZ_cfg_denoiser' has no attribute 'SDKSampler'

### ISSUE THREAD

**Issue by Sxrjs2010** [jags111/efficiency-nodes-comfyui#164]
Prompt executed in 1099.12 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
adjective: None
Aesthetic: None
Anime: None
artist: None
breast_state: None
camera: None
camera_angles: None
clothing_state: None
clothing_style: None
composition: None
depth: None
environment: None
face: None
Fantasy: None
filter: None
focal point: None
focus: None
Gothic: None
Halloween: None
lighting: None
Line_Art: None
LUTs: None
materials: None
milehigh: None
mood: None
Movie_Poster: None
nouns: None
preposition: None
Punk: None
subject: None
theme: None
timeofday: None
Travel_Poster: None
verbing: None
text_positive: Extremely detailed,

The cottage by the lake. A yacht on the water. The sun setting.

<lora:Artistic Image Enhancement v1.1 Lite:1>
<lora:The_Dark_Side_of_the_Earth:0.2>
text_negative: ac_neg1, ac_neg2, ZipRealism_Neg, Zip2D_Neg, busty, blemishes, nude, 
text_positive_styled:  Extremely detailed,

The cottage by the lake. A yacht on the water. The sun setting.

<lora:Artistic Image Enhancement v1.1 Lite:1>
<lora:The_Dark_Side_of_the_Earth:0.2>   
text_negative_styled:  ,  ,  , ac_neg1, ac_neg2, ZipRealism_Neg, Zip2D_Neg, busty, blemishes, nude, 
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
----------------------------------------
Eff. Loader SDXL Models Cache:
Ckpt:
  [1] zavychromaxl_v60
Lora:
  [1] base_ckpt: zavychromaxl_v60
      lora(mod,clip): DreamARTSDXL(0.2,0.2)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/studio-lab-user/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/studio-lab-user/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/studio-lab-user/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/studio-lab-user/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 2246, in sample_sdxl
    return super().sample(sdxl_tuple, noise_seed, steps, cfg, sampler_name, scheduler,
  File "/home/studio-lab-user/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 713, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "/home/studio-lab-user/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 483, in process_latent_image
    comfy.samplers.KSampler = smZ_cfg_denoiser.SDKSampler
AttributeError: module 'efficiency-nodes-comfyui.py.smZ_cfg_denoiser' has no attribute 'SDKSampler'

Prompt executed in 54.10 seconds

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/137243324/7d02484b-eb72-476b-a445-ab5bdc20f3ad)

I'm getting an error using Noise Control Script, Highres-Fix Script, Tiled Upscaler Script, can you help me?

**Comment by jags111** [comment]
will chk this

**Comment by Sxrjs2010** [comment]
Thanks a lot.

**Comment by flyricci** [comment]
I have the same problem. How did you solve it?

**Comment by quanzaiyu** [comment]
I encounter the same problem.

**Comment by ytoaa** [comment]
me too

**Comment by jags111** [comment]
resolved this by the updates in the python scripts already. if you still face an issue open a new thread with workflow.

**Comment by yinghuan007** [comment]
> resolved this by the updates in the python scripts already. if you still face an issue open a new thread with workflow.

sorry, i didn't get what you mean
