### ISSUE TITLE
Highres-Fix Scripts node content reset to "NaN" after load

### ISSUE THREAD

**Issue by LiJT** [jags111/efficiency-nodes-comfyui#166]
I have the same issue too! The highres-fix will reset to its "NaN" value when reloading the workflow!
image

![1](https://github.com/jags111/efficiency-nodes-comfyui/assets/11270197/f9dcdf8f-c5b6-4d3d-8075-4e7484c3abdc)

**upscaled_by**, **hires_steps** and **denoise** will become NaN
and **iteration** will reset to 2, for some wierd reason

![2](https://github.com/jags111/efficiency-nodes-comfyui/assets/11270197/3858b943-e226-4b04-9fd6-1edb1a0b60a3)

I also found out that, when you set the **upscale_type** to **Both**, this node will revert to **NaN** value no matter what you do... 
This is definitely a bug
@jags111 Would you please kind enough to fix it? Thanks in advance dude!

this is my workflow attached.
[Playground.v2.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15023098/Playground.v2.json)

**Comment by oliverban** [comment]
I was just about to come and post about this. Yes, this is happening for several people I know using this! :) It seems it is not being serialized and therefore not written to generation info...or something!? :D Would be awesome if this could be fixed! <3

**Comment by gonzalu** [comment]
Confirmed for me as well. Really annoying to have to remember my HiRes Fix settings :( 

This combined with the RNG Seed not working properly and I find myself looking for an alternative node suite that comes close to Efficient Nodes :/

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/32348862/a234ea65-8ee0-4996-ba3f-668a5f90cfdf)

**Comment by Wladislav** [comment]
Please update so that it works fine, I have NaN too.

**Comment by oliverban** [comment]
@jags111 hey, can we get some eyes on this? Thanks so much for keeping this nodes alive, they are really well beloved by the community! Old workflows don't have this problem, so there was something in the update that made this happen! :) I've heard that the node is just not "registered" with ComfyUI or something on startup, and that is why the NaN's are happening. Hopefully an easy fix! <3

**Comment by BlackWyvern** [comment]
Chiming in that the script will revert to NaNs every time you hit undo as well. Hideously annoying.

**Comment by Shinihime** [comment]
I fixed it and made a pull request.
If you wanna fix it locally yourself before this fix is merged: [https://github.com/jags111/efficiency-nodes-comfyui/pull/183/files](url)

**Comment by jags111** [comment]
done and completed and if any further raise a new issue
