### ISSUE TITLE
vae and denoiser question

### ISSUE THREAD

**Issue by derpmagician** [jags111/efficiency-nodes-comfyui#167]
![chrome_3HWhsUPkht](https://github.com/jags111/efficiency-nodes-comfyui/assets/5251673/cfb25ad6-5560-419d-89e3-9e975372cb3a)

Lets say i want to use a model that has a vae included, the Eff loaders only have the option to select a vae but is there a way to indicate that i want to use the vae in the model using the eff loader?
Also is there a way to indicate a denoise in the Eff ksampler?

I would put this in the Discussions tab but nobody responds there

**Comment by jags111** [comment]
Baked VAE means it is using the checkpoint VAE. If you want to use a separate VAE you can add it there. regarding denoise it can be controlled direct or you can add a external float for same.
