### ISSUE TITLE
Error occurred when executing KSampler (Efficient)NoneType object has no attribute 'shape

### ISSUE THREAD

**Issue by zhuolinj** [jags111/efficiency-nodes-comfyui#171]
Error occurred when executing KSampler (Efficient)
NoneType object has no attribute 'shape
File“H:iComfyuI-aki-v1.3lexecution.pyline 15l, in recursive executeoutput data, output ui = get output data(obi,input data all)File "H:\ComfyuI-aki-v1.3lexecution.py"line 8l, in get output datareturn_values = map node over list(obi,input _data_all, obj.FUNCTION, allow_interrupt=True)File“H:ComfyUI-aki-v1.3lexecution.py”,line 74,in map node_over listresults,append(getattr(obj, func)(**slice dict(input data all, i)))File "H:\ComfyuI-aki-v1.3\custom_nodes\efficiency nodes-comfyui\efficiency nodes.py", line 713, insamplesamples, images, gifs, preview = process latent_image(model, seed, steps, cfg, sampler name.s cheduler,File "H:\ComfyuI-aki-v1.3\custom nodes \efficiency nodes-comfyui efficiency nodes.py", line 533, inprocess latent imagesamples = KSampler.sample(model,seed, steps,cfg, sampler name, scheduler, positive, negative,File "H:\ComfyuI-aki-v1.3nodes.pyline 1344.in samplereturn common ksampler(model.steps, cfg,sampler name, scheduler, positive, negati

seed)File “H:\ComfyuI-aki-v1.3lcomfyisamplers.py", line 644, in sampleoutput = self.inner sample(noise, latent image, device, sampler, sigmas,denoise mask, callback,disable pbar, seed)File "H:\ComfyuI-aki-v1.3\comfyisamplers.py",， line 623,in inner_samplesamples = sampler.sample(self, sigmas,extra args,callback, noise,latent image, denoise maskdisable pbar)FileH:ComfyUI-aki-v1.3lcomfyisamplers.py”,line 534,in samplesamples = self, sampler function(model k, noise, sigmas, extra args=extra args, callbackk callbackdisable=disable pbar, ***self.extra options)File “H:\ComfyuI-aki-v1.3\python\lib\site packages(torchiutils\_contextlib.py", line 115, indecorate context
return func(*args,**kwargs)File "H:\ComfyuI-aki-v1.3\comfy\k diffusion\sampling.py", line 154, in sample_euler_ancestraldenoised = model(x,sigmas[i]* s in, **extra args)File “H:\ComfyUI-aki-v1.3\comfy\samplers.py", line 272, in __callout = self.inner_model(x, sigma, model_options=model options, seed=seed)FileH:\ComfyuI-aki-v1.3lcomfyisamplers.py”, line 610, in_.callreturn self.predict noise(*args, **kwargs)File H:\ComfyuI-aki-v1.3lcomfyisamplers.py", line 613,in predict noisereturn sampling_function(self,inner_model, x, timestep, self. conds. get("negative", None)self.conds.get("positive", None), self.cfs, model options=model options, seed=seed)File “H:\ComfyuI-aki-v1.3\comfy\samplers,py", line 258, in sampling_functionout = calc_cond batch(model, conds, x, timestep, model_options)File “H:\ComfyuI-aki-v1.3\comfy\samplers.py", line 192, in calc_cond batchc['control’]= control.get_control(input_x, timestep_, c, len(cond_or_uncond))File "H:\ComfyuI-aki-v1.3\comfyicontrolnet.py", line 155, in get_controlcontrol_prev= self.previous_controlnet.get_control(x_noisy, t, cond, batched number)File “H:\ComfyuI-aki-v1.3\comfyicontrolnet.py", line 184, in get_controlcontrol = self. control_model(x=x noisy. to(dtype), hint=self.cond hint, timesteps=timestep. float ()context=context.to(dtype)，yy)File "H:\ComfyuI-aki-v1.3\pythonllib\site packagesitorch\nnimodules(module.py", line 1518, inwrapped call implreturn self._call impl(*args, **kwargs)File "H:\ComfyuI-aki-v1.3\pythonllibisite packagesltorch\nnmodules(module.py", line 1527, incall_implreturn forward call(*args, **kwargs)File “H:\ConfyuI-aki-v1.3\confyicldmlcldm.py", line 295, in forwardassert y.shape[0] == x.shape[0]
关闭

**Comment by jffaust** [comment]
This is usually when the model name in the widget doesn't match an actual model file on the system (ie the model was renamed since)

**Comment by jags111** [comment]
perfect
