### ISSUE TITLE
The Seed randomize/recycle function on Efficiency KSampler seems to be broken

### ISSUE THREAD

**Issue by RogueLikely** [jags111/efficiency-nodes-comfyui#174]
The old behavior was that when you clicked randomize, it would set the seed value to -1, which allows for a new random seed to be used every new generation queued. 

Now, when clicking randomize it sets the seed to -1 for a split second, before replacing it with a random seed, which will then not change before or after generation, forcing you to manually click randomize to set a new seed. This also makes queuing multiple gens at once impossible with the KSampler alone.

**Comment by jags111** [comment]
oh it is pending to check same and will advise on the latest change

**Comment by Cornmeister** [comment]
any updates on this issue ? the Efficiency KSampler is awesome, but little unusable at the moment.

**Comment by techzuhaib** [comment]
Yes, I used global seed to fix this issue
