### ISSUE TITLE
AnimateDiff script

### ISSUE THREAD

**Issue by freber** [jags111/efficiency-nodes-comfyui#178]
Thanks for an amazing set of custom nodes; this is a game-changer.

My dear friends and I would love to see the AnimateDiff script start working again if possible.

Warm regards

**Comment by jags111** [comment]
we will not able to keep the animate script as it is resource hungry and complex so discontinue same.

**Comment by simon-kyger** [comment]
just noticed this here, can you remove the image with repo that features this node if it is no longer supported?
