### ISSUE TITLE
AttributeError: module 'comfy.sample' has no attribute 'convert_cond'

### ISSUE THREAD

**Issue by flybirdxx** [jags111/efficiency-nodes-comfyui#186]
![mmexport1716477604301](https://github.com/jags111/efficiency-nodes-comfyui/assets/26685745/7d60fff5-cc50-479b-99ce-47803bb80485)
There is a problem, comfy.sampler's 'convert cond' has been removed, but the eff code still has this code, which will cause the diagram error, please check your code and update it, thank you

**Comment by jags111** [comment]
sure thanks for the same

**Comment by jags111** [comment]
I have made a quick fix update and see if the error persists and if so please advise.
