### ISSUE TITLE
Change default tiling size to 320

### ISSUE THREAD

**Issue by bridgesense** [jags111/efficiency-nodes-comfyui#19]
If someone is using one of the tile options in a Ksampler vae_decode setting, it is due to memory restraints.

Consider lowering the default tile size from 512 to 320 in lines 454 and 457 of efficiency_nodes.py
```
        def vae_decode_latent(vae, samples, vae_decode):
            return VAEDecodeTiled().decode(vae,samples,320)[0] if "tiled" in vae_decode else VAEDecode().decode(vae,samples)[0]

        def vae_encode_image(vae, pixels, vae_decode):
            return VAEEncodeTiled().encode(vae,pixels,320)[0] if "tiled" in vae_decode else VAEEncode().encode(vae,pixels)[0]
```

**Comment by jags111** [comment]
hai okay will check and do the changes as needed.

**Comment by jags111** [comment]
completed same as it did not give any issues on changing same. Thanks for your suggestions and any improvements you feel will make this better do share.
