### ISSUE TITLE
“tuple”对象没有属性“decode”

### ISSUE THREAD

**Issue by wuyue0509** [jags111/efficiency-nodes-comfyui#190]
为什么打开controlnet会出现错误？关闭controlnet后一切正常。 执行KSampler (Efficient)时出现错误：
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/124325018/0815199f-78ef-4982-a422-d4cab01d74e2)

“tuple”对象没有属性“decode”

**Comment by wuyue0509** [comment]
I just want to use controlmet to control the background. Once I start the highres-fix  script controlnet, ksampler will get a running error. Is there any way to solve it?

**Comment by jags111** [comment]
i need to recreate the workflow to check same. if you can share the workflow will study and revert back on how to solve this

**Comment by wuyue0509** [comment]
[highres-fix script controlnet_error.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15464932/highres-fix.script.controlnet_error.json)

**Comment by wuyue0509** [comment]
ok,thank you,this is my workflow:
[highres-fix script controlnet_error.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15464933/highres-fix.script.controlnet_error.json)

**Comment by wuyue0509** [comment]
> i need to recreate the workflow to check same. if you can share the workflow will study and revert back on how to solve this
ok,thank you,here is my workflow:
[_highres-fix.script.controlnet_error.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15465079/_highres-fix.script.controlnet_error.json)

**Comment by wuyue0509** [comment]
> i need to recreate the workflow to check same. if you can share the workflow will study and revert back on how to solve this
ok,thank you,here is my workflow:
[_highres-fix.script.controlnet_error.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15478882/_highres-fix.script.controlnet_error.json)

**Comment by jags111** [comment]
okay will check this

**Comment by jags111** [comment]
the workflow uses the control net twice and also better to use the CN script module for same. if you use any others then the mismatch of the tensors will give error in the run. Hope it is clear.
