### ISSUE TITLE
Tiled Upscaler Script problems

### ISSUE THREAD

**Issue by yuzi1211** [jags111/efficiency-nodes-comfyui#191]
hi，my brother,I encountered a problem when using the Tiled Upscaler Script,

“Error occurred when executing KSampler (Efficient):
module 'comfy.sample’ has no attribute 'get_additional_models' ”

how should I solve it?
thanks!
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/164524683/6c640acb-6378-4568-8fe5-aade25838835)

**Comment by mamengchao** [comment]
@jags111 
Any workflow using the "Tiled Upscaler Script" can be reproduced
[Untitled Flow1.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15487409/Untitled.Flow1.json)

**Comment by yuzi1211** [comment]
OK, my brother, here it is
![QQ截图20240530011405](https://github.com/jags111/efficiency-nodes-comfyui/assets/164524683/a63b844f-8b38-42c3-a20a-cba2f8a517ce)
.

**Comment by yuzi1211** [comment]
[test2.json](https://github.com/jags111/efficiency-nodes-comfyui/files/15488458/test2.json)

**Comment by jags111** [comment]
I see one issue and updating same

**Comment by jags111** [comment]
okay updated the script and code. so kindly update eff nodes repo
<img width="809" alt="2024-05-31_18-35-52" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/f8997486-6bbf-43ca-a950-c4eee120e26e">
test same and share your results. I did not do proper tile settings and just took a run to check all okay.

**Comment by yuzi1211** [comment]
oh,thanks,bless you every day！my brother。
