### ISSUE TITLE
[Bug] Efficient Loader expands vertically

### ISSUE THREAD

**Issue by bobcate** [jags111/efficiency-nodes-comfyui#195]
Sometimes I find all the `Efficient Loader` nodes in my workflow expanded vertically, like this:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/34423403/af0a5c1f-89e6-4a40-9d41-639b49edfd88)

Found a way to reproduce.

**Comment by bobcate** [comment]
Steps to reproduce:
1. Open a brand new, empty workflow.
2. Add an `Efficient Loader` node.
3. Set the `lora_name` widget to any lora.
4. Mark with a reroute node where the `Efficient Loader` ends on the vertical axis.
5. Save the workflow.
6. Load a different workflow.
7. Load the initial workflow back in.
8. See that the `Efficient Loader` expanded and went past the marker reroute node.

The key here is the `lora_name` widget. This issue doesn't happen when it's set to `None`

**Comment by jags111** [comment]
this is the problem that occurs due to javascript having some issues with the comfyUI and if you reload that goes away.
