### ISSUE TITLE
Thank you for the branch version.

### ISSUE THREAD

**Issue by liulsg** [jags111/efficiency-nodes-comfyui#2]
Thank you so much for the branch version.

**Comment by jags111** [comment]
awesome no issues..

**Comment by alessandroperilli** [comment]
Yes, thank you @jags111. My workflow depends on some of these nodes and I hope they will stay alive as much as possible.

I opened a couple of issues in the original repo. Let me know if you want me to reopen them here.

**Comment by jags111** [comment]
Hai I have been following your threads in twitter and also your webpage. Awesome and let me know as i am just updating almost all the nodes in the pipeline and just check if any of them is fixed or not . You can always add the issues back here so I can attend to them . As I just took the change today it may be some of them may take a little time to sort out,. Thanks

**Comment by alessandroperilli** [comment]
Thank you for following. Your work is much appreciated, no matter how slow, and you'll see many people who use the Efficient Nodes will be grateful.

I re-opened my two issues from the original repo.

**Comment by jags111** [comment]
no issues and let me know the progress and again some major changes in comfyUI repo itself today.

**Comment by jags111** [comment]
okay thanks everyone here and do share your feedback to make this better and will keep a chase on same.
