### ISSUE TITLE
Not an Issue, but a Thank you!!!

### ISSUE THREAD

**Issue by aegis72** [jags111/efficiency-nodes-comfyui#20]
Dude, thanks for forking this, as I love these nodes and was sad to see that Luciano wouldn't be maintaining them. I was about to rip/replace the use of these from my Workflows but then saw in the issue post there that you forked it. Will throw some support your way come payday.

**Comment by jags111** [comment]
awesome and thanks and if any support or improvement you suggest will take it forwaard

**Comment by h3clikejava** [comment]
Thank you very very very much! I love u so much!
