### ISSUE TITLE
comfyui version b1fd26f  error

### ISSUE THREAD

**Issue by sanhedasheng** [jags111/efficiency-nodes-comfyui#200]
Starting with version number [b1fd26f](https://github.com/comfyanonymous/ComfyUI/commit/b1fd26fe9e55163f780bf9e5f56bf9bf5f035c93), efficiency-nodes-comfyui does not work and quits with an error halfway through.

I am using intel_xpu.

---------------------------------------------
b1fd26f code    
        #TODO: more reliable way of checking for flash attention?
        if is_nvidia(): #pytorch flash attention only works on Nvidia
            return True
        if is_intel_xpu():
            return True
    return False

**Comment by jags111** [comment]
can you try the FOOCUS version of effeciency sampler and check if it gives error

**Comment by sanhedasheng** [comment]
I don't know what is FOOCUS version,  but I have the others test.

Today, I tested comfyui version b1fd26f, released 2024-06-05, and tested several earlier versions of efficiency-nodes-comfyui, all of which crashed and quit the program.

Then, tested the latest version of comfyui (bb1969c), the program no longer crashes, efficiency-nodes-comfyui behaves normally, but SDXL runs out of the black picture.
![2](https://github.com/jags111/efficiency-nodes-comfyui/assets/162656882/35593ab1-de7c-446a-aa66-3b2b2cb8c27c)
picture is newsest comfyui  and efficiency-nodes-comfyui  can't support SDXL

**Comment by jags111** [comment]
sdxl base needs refiner.. so it is not converting the same.. you need steps for base and steps for refiner.. May be that is the issue. Try any other standard SDXL model it will work.

**Comment by jags111** [comment]
Hai i realized that SDXL loader with Tuple and SDXL sampler are done with the intention of using base + refiner workflows. SO if you don't add refiner it will throw black and empty image.
I have
<img width="918" alt="2024-06-18_13-01-00" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/2a8dd346-8315-4b38-b1ae-64385593653a">
 added a use case with a standard SDXL model for both base and refiner here which should give a clear idea on same.

**Comment by sanhedasheng** [comment]
![eee](https://github.com/jags111/efficiency-nodes-comfyui/assets/162656882/a0f20a99-2595-4400-b288-faff24ee8a6f)
I added a refiner model, same as the base model. I still return a black picture .
I guess it has something to do with the fact that I am using intel xpu.

**Comment by sanhedasheng** [comment]
![ccc](https://github.com/jags111/efficiency-nodes-comfyui/assets/162656882/4776b09a-5aba-4d50-810a-3aec55e06e73)
![ddd](https://github.com/jags111/efficiency-nodes-comfyui/assets/162656882/ff7a5995-0d70-4a83-8205-d3292c624012)

Base model plus refiner model. Program crashes.

**Comment by jags111** [comment]
not sure .. it is to do with the basic packages of Torch having some issues.. so recheck how to have all that sorted and run some basic  tests with your torch installation from comfy UI main package and test same.

**Comment by sanhedasheng** [comment]
All right.
Thank you.

I'm using back to the early version of comfyui, because your plugin is a must have for me.

This kind of problem may be solved without realizing it, comfyui's ecology has always been full of variables.

**Comment by sanhedasheng** [comment]
Hello.  The problem has been solved.
I reinstalled comfyui, reinstalled your plugin.
Now I am able to use your plugin with the latest version of comfyui, and SDXL is working fine.
