### ISSUE TITLE
[Question] How do I connect the loader to a dynamic prompt (such as Plush - prompt enhancer)

### ISSUE THREAD

**Issue by aminpaks** [jags111/efficiency-nodes-comfyui#204]
Hi,

Thanks for these set of amazing nodes. I'm new to using these nodes, and I'm wondering how can I connect a dynamically created text to the loader. Usually these nodes' output (such as Plush) is string.

**Comment by jags111** [comment]
can you highlight this with an example

**Comment by aminpaks** [comment]
There are many examples, an image may help. I'd like to connect the `LLMprompt` to `CLIP_POSITIVE`:
<img width="1037" alt="image" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9244395/5f32c4d0-4ba1-46d7-9f5e-6f60ee853599">

**Comment by aminpaks** [comment]
Learnt about the advanced widget to input. This can be closed.
