### ISSUE TITLE
Cant use Scheduler Selector anymore

### ISSUE THREAD

**Issue by Light-x02** [jags111/efficiency-nodes-comfyui#208]
I recently updated comfyUI and ever since then I cannot use the scheduler selector. On any sampler node (face detailer / ksampler) where I change the scheduler from a widget to input, it wont let me attach the scheduler selector to it.

I've used these workflows for months without issue, but now anytime I import one of my previous workflows using previous outputs, they fail on the scheduler inputs. If I change it to a widget it works just fine.

anyone able to explain why this happens now?

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/105165695/6c39a1e0-df73-4add-804d-2ea9b0fc8401)

**Comment by Light-x02** [comment]
Solved by going back to the previous version of "efficiency-nodes-comfyui".

**Comment by jags111** [comment]
I will need to look in to this and update.

**Comment by jags111** [comment]
update to the changes made to the repo and check if the same is any more an issue. Thanks

**Comment by Light-x02** [comment]
Hello, the problem is still there. Here's a video of the problem.
https://github.com/jags111/efficiency-nodes-comfyui/assets/105165695/ccb853bb-0ad7-41d4-98fd-c1d9c3ebbd0d

**Comment by jags111** [comment]
okay let me review this

**Comment by jags111** [comment]
any scheduler addition will give raise to issues due to the fact a recent update to comfy UI needs code changes to all schedulers. so i am using the native implementation done in eff nodes.
<img width="1095" alt="2024-06-23_18-11-03" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/31458d34-d012-4a33-9d51-3f392a0a0c2a">

**Comment by Light-x02** [comment]
So it won't be compatible any more?

**Comment by Light-x02** [comment]
Solution found: With this node which comes from "SD PROMPT SAVER" I was able to link the scheduler. 
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/105165695/887c8f90-416d-4b3b-8c06-7b223e7004e3)
