### ISSUE TITLE
Resolution cannot be well customized

### ISSUE THREAD

**Issue by AlexanderDash** [jags111/efficiency-nodes-comfyui#22]
![QQ浏览器截图20231109001220](https://github.com/jags111/efficiency-nodes-comfyui/assets/134115886/e13af1ea-24b8-4a89-bdf2-039c8842c651)
If I input a width of 600 and a height of 800, it will become 576 and 832. What should I do

**Comment by jags111** [comment]
Please note all resolutions for the input sizes have to be in multiples of 64 or their divisible only meaning 32, 16 etc as else it will give a tensor multiplication error as is standard for the latent. If you need a custom size then you need to use a different algorithm that will compute the same and provide the latent for it.  It is best for you to sperate the latent size out as a separate Input and use same using size input or latent input nodes.

**Comment by jags111** [comment]
hope i have answered your question as the tensors have to match in image generation to avoid errors
