### ISSUE TITLE
KSampler (Efficient) won't accept scheduler input

### ISSUE THREAD

**Issue by OliverCrosby** [jags111/efficiency-nodes-comfyui#231]
I used to be able to input the scheduler for the KSampler (Efficient) node. After updating it doesn't accept the input, and I can't find a node that outputs anything the KSampler will accept as input for the scheduler.

**Comment by jags111** [comment]
oh i need to check this and will update

**Comment by jags111** [comment]
I checked and here is the results. possibly compatible issue with the node selector or change the scheduler nodes as that is the one causing the errors.

<img width="1077" alt="2024-08-21_11-20-05" src="https://github.com/user-attachments/assets/f951e1c2-43cb-44fe-8ee9-c56168cc7224">

**Comment by jags111** [comment]
Else share your workflow so can check it

**Comment by OliverCrosby** [comment]
To clarify, it's the scheduler that won't connect. The sampler name works, but if I try to connect the scheduler, the input dot goes bright as if it would accept the input, but when I try to attack it it doesn't connect.

![Untitled-3 copy](https://github.com/user-attachments/assets/4c2f1f9f-3308-491b-a031-af7878bbd225)

**Comment by jags111** [comment]
the code is such it is not compatible with the K sampler code so it will not link with the scheduler selector - the node that you selected. it will clash with the sampler execution so cannot be applied as such. you need to hunt for another scheduler selector which is matching same. so the current node you are trying will not work.

**Comment by OliverCrosby** [comment]
OK, thanks, I'll look around for another node for the scheduler input. There used to be a few that would work, so maybe I'll have to make something custom. What is the ksampler expecting as an input for the scheduler?
