### ISSUE TITLE
HighRes-Fix Script 211

### ISSUE THREAD

**Issue by SistemciTR** [jags111/efficiency-nodes-comfyui#241]
![Error](https://github.com/user-attachments/assets/9af40302-a989-4802-8e44-c8d599c5b831)
got prompt
Failed to validate prompt for output 18:
* HighRes-Fix Script 211:
  - Value -1 smaller than min of 0: seed
Output will be ignored
Failed to validate prompt for output 10:
Output will be ignored
Prompt executed in 0.02 seconds

**Comment by KuroiMatoO** [comment]
I have exactly the same problem, have you managed to solve it?

**Comment by twe00074** [comment]
Click on "use the same seed" then set it to any value > -1. After this you can uncheck it, if you want to use the same
