### ISSUE TITLE
error happened when replicating animatediff&highresfix scripts workflow

### ISSUE THREAD

**Issue by joachim508** [jags111/efficiency-nodes-comfyui#25]
![screenshot](https://github.com/jags111/efficiency-nodes-comfyui/assets/150675441/1c0153fe-8567-4c33-a766-292c4dcc6edf)
hi,when i was trying animatediff&highresfix scripts workflow,this error message pops up when the during the sampling process
"local variable orig_maxium_batch_area referenced before assignment",the highres fix scripts works fine on single picture.
also my highres fix scripts doesnt show controlnet options,i tried reinstalling but it didnt work. is there a solution? thx!

**Comment by jags111** [comment]
can you share the workflow or place where this error occurred so I can reproduce same to check and do necessary changes. Thanks

**Comment by jags111** [comment]
On hires fix.. let me rerun same and update is this an issue or some settings got changed.

**Comment by joachim508** [comment]
![Uploading image.png…]()

error shows up when attaching these nodes to the sampler node,it seems its because the comfyui updated and animate diff dont yesterday

**Comment by hurkomendiguren** [comment]
Same error with a different workflow, I Updated Comfy UI and it worked for me.

**Comment by joachim508** [comment]
> Same error with a different workflow, I Updated Comfy UI and it worked for me.

yes after updating comfyui the error is gone,thank you
