### ISSUE TITLE
Changes to aesthetic scores don't trigger new generation with KSampler Advanced until ComfyUI restart 

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#3]
I'm not 100% sure this is about the KSampler Advanced node, but I'll flag it anyway. 

In the following situation, with a fixed seed, a change in the `aesthetic score` values entering the `CLIPTextEncodeSDXLRefiner `node, won't push the `KSampler Advanced` node to generate a new refined image. It will simply regenerate the same image, as if no parameter was changed.

<img width="1092" alt="Screenshot 2023-10-26 at 10 23 55" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/6d8e6b75-3de7-4a2b-bcdf-e41ea667d2ec">

To force the generation of an image that takes into account the modified aesthetic score values (all other things equal), I have to interrupt ComfyUI and restart it. As if something gets cached when it shouldn't*.

*I have a similar problem when I change the VAE in the `Efficient Loader` node: if I change the VAE setting from `baked VAE` to a specific VAE file, that is taken into account during the new generation. However, if I revert back to `backed VAE` for the subsequent generation, ComfyUI still tells me that it's using the specific VAE file. I have to interrupt ComfyUI and restart it to see the correct VAE setting being picked up.

It feels like something is aggressively cached when it shouldn't.

---

I recommend reading the follow-up comments of other users in the [original Issue](https://github.com/LucianoCirino/efficiency-nodes-comfyui/issues/222) as, apparently, this problem manifests itself in many different ways.

**Comment by Yaeph** [comment]
My CN is cached hard too and I'm using default ComfyUI Ksampler. CN is working even when it is bypassed >_>
![fBdBGFE](https://github.com/jags111/efficiency-nodes-comfyui/assets/141271455/9d367a08-c3c1-4373-b7c7-de7b029fa02c)

**Comment by jags111** [comment]
control net cache is coming from comfy backend and may be need to clear cache to make better one . check manager for same.

**Comment by gshawn3** [comment]
I noticed the same problem with conditioning changes not causing the Efficient KSampler to trigger any new generations.

Here are simple repro steps:

1) Add an Apply Control Net node and wire up its conditioning outputs to the Efficient KSampler conditioning inputs.
2) Set the ControlNet strength to 1.0.
3) Generate an image.
4) Change the ControlNet strength to 0.0.
5) Attempt to generate an updated image.

The Efficient KSampler node is not triggered as expected, and instead passes its previous/cached generation from step 3.

If you replace the Efficient KSampler with a standard KSampler, Step 5 generates a new image, as expected.

**Comment by jags111** [comment]
we will need to relook at this issue and if it still persists share a workflow to test.
