### ISSUE TITLE
New LCM-LoRA seem to have no effect on image generation speed

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#30]
I've seen videos of people loading the new LCM-LoRAs greatly reducing the image generation time. 

However, loading one of them via the `Efficiency Loader` node seems to have no effect on my system:

<img width="488" alt="Screenshot 2023-11-15 at 15 21 49" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/f84498da-1f26-4c12-9adb-a6d78c679141">

The image generation speed remains identical.

It might well be that, despite what I read, these new LoRAs don't support Apple MPS, but I wanted to flag it just in case it's a problem with how the LoRAs are loaded by the Efficient Loader node.

Thank you.

**Comment by spinagon** [comment]
It doesn't decrease iteration time, it decreases the number of steps needed.
So to make generations faster, you need to decrease the steps (4 to 8 range works well)

**Comment by jags111** [comment]
hey i tried again and for an instant painting app workflow and seems to be having no issues and generating at super cool fast speeds. May be i will give a link to a video using same.
https://www.youtube.com/watch?v=ZF1GJasG7kc
check out this workflow here and use case.
<img width="855" alt="2023-11-18_13-25-21" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/5a02cd42-28e3-4308-8a0c-a6b4360b8a9b">

**Comment by alessandroperilli** [comment]
OK. Now I better understand the point. And, after tests, I can see the LCM-LoRA works as intended in the Efficiency Loader node. Thank you both for the help.
