### ISSUE TITLE
AttributeError: module 'comfy.model_management' has no attribute 'batch_area_memory'

### ISSUE THREAD

**Issue by blueroutecn** [jags111/efficiency-nodes-comfyui#36]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/llm/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/llm/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/llm/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/llm/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 2215, in sample_sdxl
    return super().sample(sdxl_tuple, noise_seed, steps, cfg, sampler_name, scheduler,
  File "/home/llm/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 700, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "/home/llm/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 634, in process_latent_image
    samples = TSampler().sample(model, tile_seed, tile_size, tile_size, tiling_strategy, tiling_steps, cfg,
  File "/home/llm/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_tiled_samplers.py", line 314, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
  File "/home/llm/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/bnk_tiled_samplers.py", line 126, in sample_common
    comfy.model_management.load_models_gpu([model] + modelPatches, comfy.model_management.batch_area_memory(noise.shape[0] * noise.shape[2] * noise.shape[3]) + inference_memory)
AttributeError: module 'comfy.model_management' has no attribute 'batch_area_memory'

after update all, my workflow show error.

**Comment by jags111** [comment]
need to check this and update..

**Comment by cedarconnor** [comment]
Error occurred when executing KSampler (Efficient):

module 'comfy.model_management' has no attribute 'batch_area_memory'

  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 700, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 634, in process_latent_image
    samples = TSampler().sample(model, tile_seed, tile_size, tile_size, tiling_strategy, tiling_steps, cfg,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 314, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py", line 126, in sample_common
    comfy.model_management.load_models_gpu([model] + modelPatches, memory_required=(noise.shape[0] * noise.shape[2] * noise.shape[3]) + inference_memory)



After updating everything, I also got this error.

![EFF_TiledscriptWorkflow](https://github.com/jags111/efficiency-nodes-comfyui/assets/2381595/b9503c3b-131d-422f-8735-5c9f48f1599e)

**Comment by hanetyb** [comment]
yes, i meet same issue, i have to disable the tiling strategy. then it does well.

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/136415996/fbc73534-29d4-4d3d-bba1-6e8cf7bdb319)

**Comment by jac1963** [comment]
Looks like \custom_nodes\efficiency-nodes-comfyui\py\bnk_tiled_samplers.py is out of sync with recent changes made to comfy.model_management module.

**Comment by jags111** [comment]
already this corrected and may be an update on same is needed. Batch area memory error is still giving an issue will check again and update here..

**Comment by jags111** [comment]
I have corrected this file as of now and please check if it is running smooth. Thanks

**Comment by hanetyb** [comment]
it works now after installed, its very wired that its succesfull to git pull but file none any update, so reinstall to reslove. thanks for the hellp

**Comment by hanetyb** [comment]
one new issue happens the tile is resloved, but i found the template of Eff_annimantedDiff is failed to run. it works before upgrade.
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/136415996/9f38c9b1-7547-4737-9274-4ec93af053cf)

**Comment by jags111** [comment]
the script needs a change and not been able to update same so far as changes are too fast on animate diff

**Comment by hanetyb** [comment]
Thanks for the sharing.

**Comment by jags111** [comment]
will update further on this soon and closing this thread
