### ISSUE TITLE
Error running Efficiency Node Sampler on M1 MacBook Pro Max 64g

### ISSUE THREAD

**Issue by GoldmanOz** [jags111/efficiency-nodes-comfyui#37]
Having this error when running a workflow I used to run, hitting the Efficiency Node KSampler and returning the following error..All updates done with Comfy and Efficiency Nodes.  M1 MacBook Pro Mx 64g

<img width="780" alt="Efficiency Nodes" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/139660390/4f9c250a-257a-4ef2-966e-a4e441cd382d">

**Comment by jags111** [comment]
I am not familiar with the Mac related issues and will check if any solution is possible and update
