### ISSUE TITLE
[BUG] Latest update broke the way the custom node handles the Seed 

### ISSUE THREAD

**Issue by LuluViBritannia** [jags111/efficiency-nodes-comfyui#38]
Hey,
Not sure whether it's due to ComfyUI update or that custom node, but after updating everything, the behavior of the Efficient Sampler is weird. It switches between random and fixed seed on its own, and what it shows visually doesn't correspond to what is programmed to happen. For example, if I see a big number, I assume the Seed is fixed. But if I generate something, suddenly it's actually doing a random generation. Another related issue: if I put -1 in the Seed box, then I click on any other node, suddenly the Seed becomes a fixed one.

What happened?

**Comment by jags111** [comment]
can you share your workflow where this happened or some clue visual so can ascertain what is wrong with which node. This will help sort the problem . Thanks

**Comment by LuluViBritannia** [comment]
https://github.com/jags111/efficiency-nodes-comfyui/assets/14148607/3e20d572-17a7-493c-a38c-58a2b852e2c4

I made a video of the issue (should have started by that, sorry!). By doing so I got a bit more information on the matter.
As you can see in the video, just cliking on another node makes the seed go from -1 to a random number, which would make you assume it's in fixed mode. But the generated image is random despite what the KSampler shows!

The first weird sign is, when I create the node, the seed is already set to a random number.

If it's not a widespread issue, it could come from my setup. I updated everything related to ComfyUI, so who knows what I broke, lol.

**Comment by LuluViBritannia** [comment]
Yes, I know that, the problem is it doesn't, currently. I showed it in the video. As soon as I click on another node, the number switches FROM -1 to a random number (random nulmber should mean fixed seed), except it's just a visual change.

I'd love to remove the node conflict, but which one should I remove? By the way, the error mutated, lol. Now it says this:
Conflicted Nodes:
Image Overlay [Comfy_KepListStuff], NNLatentUpscale [ComfyUi_NNLatentUpscale], LatentUpscaler [SD-Latent-Upscaler]

What the F is happening? xD!

**Comment by ManOrMonster** [comment]
I'm getting this too. 
<img width="494" alt="image" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/3925151/542bf29a-883e-4c89-b061-62160313ec61">

**Comment by ogurikaz** [comment]
I believe I've been able to isolate what is causing this.

If you have ever installed the "use everywhere" custom nodes;
The following folder should exist: C:\AI\ComfyUI\ComfyUI\web\extensions\use_everywhere

Even if you disable, or even uninstall the "use everywhere" custom nodes, the folder may remain here.

Removing this folder (or moving it somewhere else) stops the behaviour of the seed jumping whenever clicking on a node.

I have not dug into WHY the code in here triggers it though, but it is a good place to start digging.

**Comment by LuluViBritannia** [comment]
Oh. I do have Use Everywhere.
... Well, if I have to choose, I will choose UE, lol. If someone wants an alternative to Efficiency Nodes : get Impact Pack and use its Global Seed, it has the option to control before generate (i.e how the Seed works in Efficiency Node). Rgthree also has a custom node for Seed control before generation.

**Comment by LiJT** [comment]
> I'm getting this too. <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/3925151/287325519-542bf29a-883e-4c89-b061-62160313ec61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjgxODAsIm5iZiI6MTcwMTk2Nzg4MCwicGF0aCI6Ii8zOTI1MTUxLzI4NzMyNTUxOS01NDJiZjI5YS04ODNlLTRjODktYjA2MS02MjE2MDMxM2VjNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDdUMTY1MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcwOGJmMjlkNmY4YjljYWM2NTU3ZTU3MjZmNGVmYjM4YzUyMmQyYjQxNDRiMjk2ZTIxOTg2Y2NmMDllMDMxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iKmTxqbVCKel29MSsODBYiAseK2Njscyi6vrkTThm6U">
> 
> After unsintalling, restarting, then reinstalling and restarting, the nodes are appearing again for now though.

I have this problem too, NNlatentUpscale is not working. which is a shame...

**Comment by Thireus** [comment]
Any update?

**Comment by jags111** [comment]
for all the information is only that the node in question is kind of duplicated and so no need to worry for same as no functionality or issues with same.
<img width="762" alt="2023-12-08_19-53-37" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/f37d74c1-fc16-4efb-a9ed-294da8c9d5a2">

<img width="791" alt="2023-12-08_19-54-11" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/c6e65d96-14d4-4e6e-955a-5335ffde992c">

**Comment by jags111** [comment]
install the NN upscale and city upscale separately. check the readme.md  where i have outlined same.
