### ISSUE TITLE
Is it possible to add LoRA in HiRes-Fix Script?

### ISSUE THREAD

**Issue by zyd232** [jags111/efficiency-nodes-comfyui#39]
I noticed that, in A1111 webUI, the HiRes-Fix process is effected by the LoRAs used.
Is it possible to add LoRA in HiRes-Fix Script?

**Comment by jags111** [comment]
yes will study and update this as soon as possible

**Comment by jags111** [comment]
after checking your query ..  Already LORA gets loaded thru the efficiency loader and Hires script can work with same.
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/f48bcf9f-2322-4f5a-9459-fb27c37f78a3)

**Comment by jags111** [comment]
The hires fix is limited to certain work and if you need more flow and better then add kohya hiresfix script to custom nodes as this will boost speed and results.

check this node and it is already implemented in comfyUI recent versions.. May be the name is different in comfyUI

![image - 2023-11-25T220351 781](https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/10a4314f-9f0f-49a5-8e55-f1020d487778)
