### ISSUE TITLE
ControlNet Stack input increases KSampler Advanced Efficient image generation time proportionally to the number of active controlnets

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#4]
In the scenario below, I enabled a `CR Multi-ControlNet Stack` node with 3 controlnets (Canny, Depth, and OpenPose). The stack conditions a `KSampler Advanced Efficient` node.

<img width="1011" alt="Screenshot 2023-10-30 at 11 18 17" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/9775949/caaf613d-b00d-4ebd-8b25-055310815a8d">

Doing so enormously increases the generation time: all things equal, the SDXL base model goes **from ~3min30s / image** (I'm on a Mac...) **to ~8min50s / image**.

If I modify the stack to only use 2 controlnets, the generation time goes down **to ~6min36s / image**.

With 1 controlnet only, the generation time goes down **to ~4min51s / image**.

Is this behavior normal? I don't recall ControlNet influencing generation time in A1111 or SD Next, even when I used 3 at a time, like in this case.

(I noticed this a while ago. It's not something new. I just didn't report it before because I wasn't certain it's an anomaly)

**Comment by jags111** [comment]
okay got this and let me check same. If possible share the workflow to check where the issue comes in .. either a baked image or json of same so can check the same and update.

**Comment by jags111** [comment]
sure will check this again as major update and still getting all nodes to work smooth.

**Comment by jags111** [comment]
this behaviour comes from control net handling
