### ISSUE TITLE
Error "missing 1 required positional argument: 'control_net_name'" (non-systematic) with the 'HighRes-Fix Script' node

### ISSUE THREAD

**Issue by TheMoye** [jags111/efficiency-nodes-comfyui#42]
Hello everyone,

From time to time, I encounter an error when using the '**HighRes-Fix Scrip**t' node. Sometimes it works, sometimes it doesn't, even while strictly using the same workflow (for instance, through the '**load**' button or by dragging an image).

Here's the error:

```
Error occurred when executing HighRes-Fix Script:

TSC_HighRes_Fix.hires_fix_script() missing 1 required positional argument: 'control_net_name'

  File "C:\ArtificialIntelligence\ComfUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ArtificialIntelligence\ComfUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ArtificialIntelligence\ComfUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
```

And here's the associated workflow:

![control_net_error](https://github.com/jags111/efficiency-nodes-comfyui/assets/46683101/2e7a7268-ad12-4e0d-81d2-5dc15267d162)

ComfyUI and Efficiency Nodes are up to date.

Thank you in advance for your help! 👍

**Comment by jags111** [comment]
okay will check this out and update again

**Comment by jags111** [comment]
I have tested it multiple times and seems to be having no issues.
<img width="974" alt="2023-11-30_00-30-58" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/d6f9fa25-63b2-4805-9d2b-c5c6c7750d7a">

**Comment by TheMoye** [comment]
> I have tested it multiple times and seems to be having no issues. dont load control net with this

I can't explain it, I just restarted ComfyUI, and something interesting happened :

The last workflow created in ComfyUI loaded (the same as in my previous screenshot), I initiated the generation, and it worked.
I performed a "**clear**," inserted an "**Efficient Loader**" followed by a "**KSampler (Efficient)**," then the "**HighRes-Fix Script**": I encountered the 'control_net_name' error.

So, I closed the ComfyUI window, shut down the server with "Ctrl + C," disabled the virtual environment.
I restarted the virtual environment, relaunched ComfyUI using "python main.py," reopened the window that loaded my previous workflow: magically, the generation worked as shown in the attached screenshot.

![Capture d'écran 2023-11-29 211223](https://github.com/jags111/efficiency-nodes-comfyui/assets/46683101/53ef10ca-eeff-4262-910a-f7ba25d549ce)

However, if I delete the "HighRes-Fix Script" node and add it again, the generation crashes once more.

![Capture d'écran 2023-11-29 211429](https://github.com/jags111/efficiency-nodes-comfyui/assets/46683101/9ebdd66b-11e8-4f44-8941-de0749e188c9)

**Comment by jags111** [comment]
I think will check out the hires script node and make a default change so it will not create any further errors.

**Comment by jags111** [comment]
nope i need to find out from where this originates and plug same and will revert to you in a day or two. Thanks

**Comment by CUexter** [comment]
got the same problem, but i don't even have an option to set use control_net to fasle

**Comment by uberderf** [comment]
I can confirm that i was having the same problem, but hadn't tried cloning the control. Once i did that everything worked ok. Hope you are able to find the problem. at least i know how to get it to work temporally.

**Comment by jags111** [comment]
to all citing this issue. this node is linked to the repo of control net being available to use and so installing the same Fannovel's [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) installed to resolve this issue.

**Comment by petalas** [comment]
I seem to be getting this error again randomly even using just a pixel_upscaler (it shouldn't even need a control_net at all right?).

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/7421346/50b884dc-d565-431a-9d78-2141794a3215)

```
Error occurred when executing HighRes-Fix Script:

TSC_HighRes_Fix.hires_fix_script() missing 1 required positional argument: 'control_net_name'

File "/home/nick/git/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/nick/git/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/nick/git/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
```

I have comfyui_controlnet_aux installed too just in case and everything updated to latest (but shouldn't need it for this?)

```
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
```

@jags111 any ideas? Want me to open a new issue?

**Comment by Zak-Adelman** [comment]
I am having the same issue with pixel and latent, exact same wording for both errors, I think we need a new issue opened as well.

**Comment by petalas** [comment]
An interesting note: I restarted everything multiple times before reporting this, no luck.
But then a few hours later it worked with no error, without me making any changes.
So restarting does not reliably fix it but **_sometimes_** it does.

**Comment by AyoKeito** [comment]
Same problem, gives out `TSC_HighRes_Fix.hires_fix_script() missing 1 required positional argument: 'control_net_name'` error, with our without [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux)
`use_controlnet` option is not even there

**Comment by wuyue0509** [comment]
Why does an error appear when opening controlnet?
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/124325018/c70db27f-8c31-49d7-ab85-b11b8bc77c7f)
Error occurred when executing KSampler Adv. (Efficient):

'tuple' object has no attribute 'decode'

**Comment by wuyue0509** [comment]
Why does an error appear when opening controlnet? Everything works fine after closing controlnet. Does the script not support controlnet?
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/124325018/642b480d-616c-48b7-b904-1be6c47c8296)
Error occurred when executing KSampler Adv. (Efficient):

'tuple' object has no attribute 'decode'

**Comment by rityak** [comment]
**Found a way to solve the problem.** 
Just download any model and put it in the controlnet folder. The `control_net_name` value should not be `undefined`, even if the use of controlnet is disabled.
