### ISSUE TITLE
Want to increase file hierarchy 

### ISSUE THREAD

**Issue by liulsg** [jags111/efficiency-nodes-comfyui#43]
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/97494068/4b9a6ab3-1afa-4c21-8a48-05bdeee671d6)
I hope that the file hierarchy can be increased when loading the model, because it is very troublesome to query after there are too many models.

**Comment by jags111** [comment]
Hai the node you just show in example is from pythongosssss and can you put this query to his repo so he can modify the code.  I am not sure how same can be done from my end. Please update. Thanks

**Comment by liulsg** [comment]
@jags111 
Maybe you misunderstood me, I mean can you add such a per-file display model and lora to the efficiency node? This allows you to select models quickly.  If you don't think it's necessary, forget it.

**Comment by jags111** [comment]
oh no issues ..I was trying to figure out .. a way out
