### ISSUE TITLE
Denoising in KSampler Advanced node

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#45]
I'm working on an img2img scenario, and my usual Superman image is my source image:

![Superman](https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/3faafeb9-1fad-4a20-b6d4-815fee27e4bb)

One of the differences between the `KSampler` (left) and the `KSampler Advanced` (right) in this node suite is that the latter lacks a way to define the denoise level:

<img width="568" alt="Screenshot 2023-12-01 at 16 48 24" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/38628749-f635-4b68-a146-9f2c34af1797">

The `KSampler Advanced` node allows you to activate `add_noise`, but I see no way of controlling the amount of denoising.

Given that it's an "advanced" node, I assumed that denoising depends on the sophisticated `Noise Control Script`, but I tried it and it seems to be doing nothing to control denoise:

<img width="912" alt="Screenshot 2023-12-01 at 17 16 07" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/05dc3db6-63c5-4099-9d59-3576779c9575">

What am I missing something? Thank you.

**Comment by jags111** [comment]
May be change the source from CPU to GPU or other  options and check out the result. I will also compare and present it here for your notes. Thanks

**Comment by ghostsquad** [comment]
I'm also realizing that I'm not sure how to control denoising for img2img using the Adv. Efficient KSampler.

**Comment by JakeSSRN** [comment]
I would love to see the denoise slider from the regular efficient KSampler (and base KSampler) make it into all the advanced efficient KSamplers as well.

**Comment by jags111** [comment]
will advise on same once done. please reopen the issue as so many changes happened in scripts
