### ISSUE TITLE
[FEATURE REQUEST] - Efficient Loader supporting positive text_g & text_l as well as negative text_g & text_l

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#48]
### Summary

At the moment the `Efficient Loader` node only accepts one positive prompt input and one negative prompt input. 
However, we know that SDXL allows the splitting of each prompt into a text_g and text_l values, each going to different CLIP nodes for encoding. 

I assume that, at today, the `Efficient Loader` node simply copies the same positive prompt for text_g and text_l values, and does the same with the negative prompt. Which is exactly what the overwhelming majority of SD users are doing.

However, there might be value in differentiating the inputs for text_g and text_l. See, for example, this conversation (including my reply and others):
[https://www.reddit.com/r/comfyui/comments/189jj4e/how_do_i_push_details_in_clip_g_sdxl/](https://www.reddit.com/r/comfyui/comments/189jj4e/how_do_i_push_details_in_clip_g_sdxl/)

### Basic Example

I'm proposing that the `Efficient Loader` node features 4 prompt inputs instead of two:

- positive text_g
- positive text_l
- positive text_g
- negative text_l

When the Loader is dealing with an SD1.5 checkpoint, it would simply ignore the secondary text input.

**Comment by jags111** [comment]
yes possible and will explore and add it and any suggestions for same welcome
