### ISSUE TITLE
Cannot find or use the NNLatentUpscale Node 

### ISSUE THREAD

**Issue by LiJT** [jags111/efficiency-nodes-comfyui#51]
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/11270197/8f6a99e3-cb35-4227-9bc4-869a3c227214)

I m trying to load this upscale workflow from Latent Vision, then i noticed a problem.
[upscalecomparison.json](https://github.com/jags111/efficiency-nodes-comfyui/files/13602749/upscalecomparison.json)

I cannot seems to load this "NNLatentUpscale" node for some reason. I dont think my custom node has conflict with this one and only node right? Please show me the way what I should to do to get it working again.

I have tried removing all my custom node, and this problem still appears
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/11270197/028e99de-65e6-44db-83c8-abfa2e147662)

Is this node no longer supported? NNLatentUpscale is an awesome upscaler tool...

Thanks in advance!

**Comment by jags111** [comment]
Hai the node was suppressed for some development and will be available in some time as i will update the codes and then you can update efficiency nodes and it should be available in the manager

**Comment by jags111** [comment]
after testing due to some error I will load the latent upscale nodes through another repo and make it available .  Will add the link of the repo which you can add through the manager. For some unknown reasons the py files fail in this repo throwing a javascript error which is unconnected. That is why this two nodes were kept in lock. I will update in one hour another repo with the same node.

**Comment by jags111** [comment]
Hai okay checked and it is available in efficiency as it is now.. Just search for this node as shown;
<img width="762" alt="2023-12-08_19-53-37" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/6a437109-f2ec-4e31-9429-51be78b0eb9f">

also here is the test run with same;
<img width="791" alt="2023-12-08_19-54-11" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/3818d846-8e66-453d-95df-43c4059a4795">

**Comment by LeArchi** [comment]
Hello, I've had the same error where I cannot find NNLatentUpscale, after reading this issue thread - I tried to disable -> enable the custom node inside the comfy manager, I've tried to uninstall and installing it again, also installing the custom nodes manually from the GitHub from different branches, including the fix#46 branch. I've tried searching for the name "LatentUpscaler" and the previous "NNLatentUpscale" and cannot find them within ComfyUI. 

I could be missing something trivial, I am new to ComfyUI in general, would appreciate any help related to this particular node.

**Comment by jags111** [comment]
Hai very important ! only install using comfyUI manager to install this version. Once done go to the search bar and search for the node  "Latent Upscaler" or "NNLatentUpscale" and already it is available in search function. You don't need to do any thing else. Once done check it same and save it to node template or any where you can locate it again. This is simple to do.

**Comment by alessandroperilli** [comment]
I have the same problem, @jags111. Since you released these two new nodes (I track GitHub commits), I cannot find them via search or in the Efficient Nodes menu.

I only install and update custom nodes via ComfyUI Manager. And ComfyUI imports the suite at startup without glitches. So I'm not sure why they don't appear anywhere.

**Comment by jags111** [comment]
for some strange reason in the js file this is not coming in the eff. menu in the search bar. But just enter Latent Upscaler and you will find it or enter the other name and you will get it. I will try and see if i can update the python file with out any errors

**Comment by alessandroperilli** [comment]
It also doesn't come up with the search. It never did.

<img width="838" alt="Screenshot 2023-12-10 at 15 35 13" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/25a99461-916d-42ab-9c3a-68d388cadc51">

<img width="840" alt="Screenshot 2023-12-10 at 15 35 27" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/4bc474f9-ecbe-415d-b03b-106ada5052e1">

**Comment by alessandroperilli** [comment]
I promise you that neither appears in the search results :)

**Comment by jags111** [comment]
oh i think it is coming from the init.py issue and trying to fix same makes it even worse.. So i am going to make a workaround for same and will post again

**Comment by z0rchuh** [comment]
Yeah, still no node.

**Comment by Channel3902** [comment]
I'm having this same issue.

**Comment by jags111** [comment]
i have changed codes and still elusive and so will rewrite all links

**Comment by kowalgregy** [comment]
Same problem - looking forward to the fix

**Comment by jags111** [comment]
actually the problem is coming from the java script backend and i need to remove the links associated and test them before uploading so will be multiple tests to complete same. Once all the associated nodes are working then automatically the node names will change and reflect the same. I need to verify the java script does not affect the browser behavior and then conclude same.

**Comment by cqwcqwcqwa** [comment]
can't use this not

**Comment by jags111** [comment]
can you wait for me to give an update then you are good to go.
If you want a quick solution  please install the NN latent upscale from Manager including the city one so you are back to normal !
https://github.com/Ttl/ComfyUi_NNLatentUpscale
https://github.com/city96/SD-Latent-Upscaler

this should solve everything until this is restored
Thanks

**Comment by cqwcqwcqwa** [comment]
very thank you

**Comment by tobiaswuerth** [comment]
why include them in the first place? just let the people install it from the original repo. combining them into one download is not revolutionary and might cause conflicts and update issues.

**Comment by jags111** [comment]
it is not my doing the conflict is coming from a different issue nothing to do with the installs or links etc

**Comment by unique15** [comment]
Hi, I am still getting this "NNLatentUpscale" missing error. I also installed the github repo manually.

> can you wait for me to give an update then you are good to go. If you want a quick solution please install the NN latent upscale from Manager including the city one so you are back to normal ! https://github.com/Ttl/ComfyUi_NNLatentUpscale https://github.com/city96/SD-Latent-Upscaler
> 
> this should solve everything until this is restored Thanks

Hi, I am still getting this "NNLatentUpscale" missing error. I also installed the github repo manually.

**Comment by gshawn3** [comment]
Neither of the latent upscaling nodes are showing up for me either. I had to install them separately.
