### ISSUE TITLE
causes Comfyui manager to become unresponding

### ISSUE THREAD

**Issue by S0LTIS** [jags111/efficiency-nodes-comfyui#55]
Upon installation into node Dir. and Booting up Comfyui, Comfyui manager becomes unresponsive and fails to launch. Have taken this node in and out of the directory to duplicate the end results. It's occurred each time I put the node into the custom_node dir.

**Comment by jags111** [comment]
please install this node from comfyUI manager only as it will then do necessary backend work

**Comment by jags111** [comment]
do not install by any other means as this will make everything unstable and update all including comfy main as this is what is causing errors.
