### ISSUE TITLE
KSampler disables preview for the whole workflow

### ISSUE THREAD

**Issue by JarekDerp** [jags111/efficiency-nodes-comfyui#65]
Hi,

I think there's a bug in the node somewhere, as it disables the previews for all other KSamplers and nodes after I run it like this:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/38da3362-cf0d-4648-938b-0a9652fc0860)

So basically I don't get any previews until I either restart ComfyUI or change the setting in Comfy Manager.
When I "Set node to never" and use the normal KSampler in it's place it works just fine. Running the sampler from the screenshot just disables the previews permanently when doing a simple img2img upscaling.

**Comment by jags111** [comment]
let me review this and update

**Comment by jags111** [comment]
it neds the VAE decode to function for preview of the latent and if it is kept false the VAE is not loaded and will result in preview being blank. Try the same with VAE decode true and check same.

**Comment by JarekDerp** [comment]
I'm not talking about "Preview image" node... I'm talking about TAESD and Latent2RGB previews that are running inside of KSamplers while the image is being generated.
Here you go, with screenshots, TAESD turned on:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/c4405203-ea03-4480-9155-9c57c8b99c3b)

Running 2 KSamplers are fine, previews works fine.
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/5344c5b1-fcf7-47d9-b2c2-0ae4b48dc279)

Running Efficient KSampler once, other KSamplers stopped generating previews. Either normal Ksamplers, or "Ultimate SD Upscaler" or anything really:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/2f7c2480-bc99-4525-88b1-327ef9a04e8f)


I think your python code, in line 465 stores information about what "Preview method" was used, and then in line 685 it restores it, but I don't think that's working as intended. I think it never restores the Preview Method that was used before using Efficient KSampler.

**Comment by JarekDerp** [comment]
Just for fun, I commented out all "set_preview_method()" functions in your code, like here in line 475 and in line 495:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/eff80a13-a8df-4d67-a791-3d8d18846c24)

And now running the workflow is fine, other KSamplers are generating images with previews:
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/54577977/aad6ac69-071b-4277-aa01-015eda171359)

**Comment by jags111** [comment]
okay let me review this and give an update

**Comment by JarekDerp** [comment]
Just to add a bit, I tested it on two machines, one running Windows 10 and one running Windows 11. One using CPU and one using AMD GPU via DirectML. One has ComfyUI installed via Stability Matrix, and one is using ComfyUI portable with unstable nightly pytorch. And the problem occurs in both instances.

**Comment by jags111** [comment]
The said K sampler is not from efficiency and cannot comment on same. The ones from here are marked efficiency . it is nothing to do with same and is dependent on the VAE used and if it is plugged into the preview or not. If you delink the VAE to a sperate one you will find this problem not occur. It is the way each k sampler works and any latent to be converted to image it needs decoding to happen.

**Comment by JarekDerp** [comment]
> The ones from here are marked efficiency . it is nothing to do with same and is dependent on the VAE used and if it is plugged into the preview or not.

My god. Let's use simple words.

"KSampler (Efficient)" has bug. Bug breaks other KSamplers.
Only using normal KSamplers = everything works.
After running "KSampler (Efficient)" once = ComfyUI breaks. Normal KSamplers not working as before. I need to restart ComfyUI.
PREVIEWS INSIDE KSAMPLERS. NOT "Vae Decode -> Preview image". That one works fine. I CANNOT SEE WHAT I'M GENERATING, WHILE IT'S GENERATING.
I said lines 475 and 495 (one of them) has bug. One of them breaks ComfyUI.

Is it clear now? I know how to use ComfyUI. I'm not a noob. I know you need to decode the latent image to view it. You would realize that if you had a look at the images I posted in my previous messages.

**Comment by jags111** [comment]
okay let me review the code and update

**Comment by lenkunz** [comment]
I copy it from this https://github.com/LucianoCirino/efficiency-nodes-comfyui/issues/254

It seems like the function `set_preview_method` was unable to restore the value from preview method saved using function `global_preview_method`. on https://github.com/jags111/efficiency-nodes-comfyui/blob/c15913587f218ec17ac4208d382a789934929ae4/tsc_utils.py#L504
```python3
def set_preview_method(method):
    if method == 'auto' or method == 'LatentPreviewMethod.Auto':
        args.preview_method = latent_preview.LatentPreviewMethod.Auto
    elif method == 'latent2rgb' or method == 'LatentPreviewMethod.Latent2RGB':
        args.preview_method = latent_preview.LatentPreviewMethod.Latent2RGB
    elif method == 'taesd' or method == 'LatentPreviewMethod.TAESD':
        args.preview_method = latent_preview.LatentPreviewMethod.TAESD
    else:
        args.preview_method = latent_preview.LatentPreviewMethod.NoPreviews
```

This is because ComfyUI Manager or the other libs will set the `args.preview_method` using `latent_preview.LatentPreviewMethod` class. refer to https://github.com/ltdrdata/ComfyUI-Manager/tree/1e188d927e848ca25bd09f72d0396045a86f8d3e/__init__.py#L224
I have confirm that compare the enum against string will not equal.

Slight change like this would suffice.
```python3
# efficiency-nodes-comfyui/tsc_utils.py#L504
def set_preview_method(method):
    if method == 'auto' or method == 'LatentPreviewMethod.Auto' or method == latent_preview.LatentPreviewMethod.Auto:
        args.preview_method = latent_preview.LatentPreviewMethod.Auto
    elif method == 'latent2rgb' or method == 'LatentPreviewMethod.Latent2RGB' or method == latent_preview.LatentPreviewMethod.Latent2RGB:
        args.preview_method = latent_preview.LatentPreviewMethod.Latent2RGB
    elif method == 'taesd' or method == 'LatentPreviewMethod.TAESD' or method == latent_preview.LatentPreviewMethod.TAESD:
        args.preview_method = latent_preview.LatentPreviewMethod.TAESD
    else:
        args.preview_method = latent_preview.LatentPreviewMethod.NoPreviews
```

Edit: Remove the ComfyUI Manager from title. I just realized that this node will set the `args.preview_method` to `latent_preview.LatentPreviewMethod` enum either. And after scan other libs, it seems like using this class is a norm.

**Comment by jags111** [comment]
okay may be this needs a tweak and let me try and change same and update
