### ISSUE TITLE
Efficiency Nodes for ComfyUI Version 2.0+ NOT FOUND

### ISSUE THREAD

**Issue by yinnxinn** [jags111/efficiency-nodes-comfyui#68]
I reinstall this node many times ,  and load is totally ok. 
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/23116748/dbf88cb4-7811-47f7-bbd9-a2b72ebf493c)

but I get this error still in the page 
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/23116748/0cf5d951-a1bb-427d-bc45-a19b600956e4)

I followed the instruction from some solutions like 
https://www.reddit.com/r/comfyui/comments/17n7etb/efficiency_nodes_import_failed/

reinstall the node many times ,but sill block here. 

Anyone could help me fix this problem .

**Comment by jags111** [comment]
can you just log into Manager and reinstall same and remove any old ones if any and check your customs nodes folder for same
. Remove the old ones and reinstall and it should be good to go
check and send feedback !

**Comment by yinnxinn** [comment]
邮件已收到，谢谢

**Comment by janoist1** [comment]
I'm still having this issue. That's what I've got under `custom_nodes`:
```
custom_nodes ls
ClipInterrogate.py                ComfyUI_UltimateSDUpscale   comfyui-art-venture
ComfyUI-Advanced-ControlNet       ComfyUI_tinyterraNodes      comfyui-dynamicprompts
ComfyUI-AnimateDiff-Evolved       DTAIImageToTextNode         comfyui-mixlab-nodes
ComfyUI-Custom-Scripts            Derfuu_ComfyUI_ModdedNodes  comfyui_controlnet_aux
ComfyUI-Hangover-Nodes            OneButtonPrompt             comfyui_segment_anything
ComfyUI-Impact-Pack               ResizeAspectratio.py        efficiency-nodes-comfyui
ComfyUI-Inspire-Pack              SDXLAspectRatio.py          example_node.py.example
ComfyUI-Manager                   __pycache__                 image-resize-comfyui
ComfyUI-QualityOfLifeSuit_Omar92  cg-image-picker             rgthree-comfy
ComfyUI-VideoHelperSuite          cg-noise                    sdxl_prompt_styler
ComfyUI_Comfyroll_CustomNodes     cg-prompt-info              sdxl_utility.py
ComfyUI_FizzNodes                 cg-use-everywhere           was-node-suite-comfyui
ComfyUI_IPAdapter_plus            cg_custom_core
ComfyUI_MileHighStyler            clipseg.py
```

**Comment by yinnxinn** [comment]
邮件已收到，谢谢
