### ISSUE TITLE
[BUG?] vae_name in Efficient Loader node doesn't accept any inbound link when converted to input

### ISSUE THREAD

**Issue by alessandroperilli** [jags111/efficiency-nodes-comfyui#79]
I think I remember the following behavior was different in the past, but I might be confused. I'm not even sure it's a bug, so apologies if the tagging is incorrect.

Let's say that I want to convert the vae_name value from widget to input, like in the screenshot below. 
At that point, I would want to pass the value from the default VAE Loader node or from the SD Parameter Generator node, which I use in the AP Workflow. 

In both cases, the Efficient Loader doesn't accept the link.

<img width="1153" alt="Screenshot 2024-01-13 at 10 29 32" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/9775949/f2179771-ba07-41c6-ac30-27399aea0e95">

I know you have a lot on your plate, and supporting this custom node suite is a lot of work. So, thank you in advance for any time you'll be able to dedicate to this. Your work is highly appreciated.

**Comment by jags111** [comment]
as it is a bakedVAE  which means the VAE is coming from the original check point don't port same outside as a value as it will not accept same. so revert it back to a widget and add same
