### ISSUE TITLE
Efficiency 2.0 - the preview stopped working in all not efficiency nodes.

### ISSUE THREAD

**Issue by sborys-ai** [jags111/efficiency-nodes-comfyui#8]
Re-opened my issue from the original repo.

The issue appears as follows - if Efficiency 2.0 is not loaded in ComfyUi, the preview in all nodes works without any problems. If Efficiency 2.0 is loaded, but its nodes were not launched in the workflow, the preview also works. However, if Ksampler (efficient) was launched once, the preview in other nodes is blocked, while in Ksampler (efficient) the preview works fine. As I understood, the block occurs at the web interface level, as from the same browser I launched the workflow on a remote server ComfyUi (without Efficiency 2.0) and the preview also did not work in this case.

System: Ubuntu 23.04
Browser: Chromium 118.0.5993.88

**Comment by jags111** [comment]
will look into this and reply

**Comment by jags111** [comment]
I think it is all resolved for now . so please advise if any more issues. thanks

**Comment by jags111** [comment]
thanks for your support . check if it is repeating and if so then add a new issue
