### ISSUE TITLE
can't import these nodes

### ISSUE THREAD

**Issue by Rayray927** [jags111/efficiency-nodes-comfyui#84]
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/91202729/1eb24fc6-9f90-4498-bccb-07f867d89b0c)

**Comment by jags111** [comment]
well i need to check the issue from log to understand on same so cannot comment until i see the log

**Comment by Rayray927** [comment]
> well i need to check the issue from log to understand on same so cannot comment until i see the log
I figure it out by changing the line `from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint` to `from comfy.samplers import KSampler, KSamplerX0Inpaint.` in the `smZ_cfg_denoiser.py` file.

**Comment by jags111** [comment]
can you share your log file to understand what is the issue ass cant figure out same

**Comment by jags111** [comment]
closing this and if any further support needed please raise a new issue
