### ISSUE TITLE
Error on Comfy startup: Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Failed!

### ISSUE THREAD

**Issue by rollingcookies** [jags111/efficiency-nodes-comfyui#91]
At startup in console window, the error "Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Failed!" occurs, which does not allow to reproduce the connection of the AnimatedDiff Script node (it is not in the interface) with KSampler (Efficient) :(

Didn't help the solve problem:
Uninstalled and reinstalled ComfyUI-AnimateDiff-Evolved and efficiency-nodes-comfyui 
Updated Comfy from Manager and same via update.bat

Can anyone help me to solve the problem?

**Comment by emourdavid** [comment]
I have same problems. I installedAnimateDiff Evolved node only and it works but I don't understand why I get this warnings. I updated all nodes to latest version

**Comment by Tobe2d** [comment]
+1 
got the same issue

**Comment by jags111** [comment]
Hai the new updates in animate diff caused this issue and looking into same and updating

**Comment by jags111** [comment]
Possibly I am planning to remove the dependency on animate diff script and remove same from eff nodes as it will not work on its own.

**Comment by LuisBurdallo** [comment]
I am here for the exact same reason.

**Comment by jags111** [comment]
already the script dependency is removed and any other association of running animate diff script will be  converted to default and deprecated.

**Comment by gonzalu** [comment]
nooooooo ... :D Thank you though... it looked promising :D
